Repository gazebosim/gz-sensors, pull requests merged in 2020-11, with the labels that each got.

#55 Bump in edifice: ign-rendering5
  .github/ci/packages.apt
  CMakeLists.txt
  examples/save_image/CMakeLists.txt
Labels: 🏢 edifice

#57 Resolve updated codecheck issues
  src/PointCloudUtil.cc
Labels: 📜 blueprint

#56 👩‍🌾 Prevent segfaults on test failures, make tests verbose
  include/ignition/sensors/Manager.hh
  src/Camera_TEST.cc
  src/ImuSensor_TEST.cc
  src/Lidar_TEST.cc
  src/Manager_TEST.cc
  src/Noise_TEST.cc
  src/Sensor_TEST.cc
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: 🏰 citadel

#59 👩‍🌾 Suggestions on addressing Windows warnings
  examples/save_image/main.cc
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImageGaussianNoiseModel.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/RenderingEvents.hh
  include/ignition/sensors/RenderingSensor.hh
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImageGaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/MagnetometerSensor.cc
  src/Noise.cc
  src/PointCloudUtil.hh
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/ThermalCameraSensor.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: Windows, 🔮 dome

#63 2 to 3
  src/PointCloudUtil.cc
Labels: 🏰 citadel

#60 Fix macOS/windows tests that failed to load library
  .github/workflows/macos.yml
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: Windows, macOS, tests, 🔮 dome

#61 added thermal camera tutorial
  CMakeLists.txt
  tutorials.md.in
  tutorials/files/thermal_camera/hot_object_behind_cool_object.png
  tutorials/files/thermal_camera/thermal_camera_demo.png
  tutorials/files/thermal_camera/thermal_camera_demo_2.png
  tutorials/thermal_camera.md
Labels: 🏰 citadel
