Repository gazebosim/gz-sensors, pull requests merged in 2020-09, with the labels that each got.

#44 Merge ign-sensors2 to ign-sensors3
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/config.hh.in
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImageNoise.cc
  src/ImuSensor.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Noise.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
Labels: 🏰 citadel

#47 ⬆️ 3.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#46 3 ➡️ 4
  .github/ci-bionic/dependencies.yaml
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/config.hh.in
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImageNoise.cc
  src/ImuSensor.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Noise.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
Labels: beta, 🔮 dome

#41 Replaced common::Time for std::chrono
  examples/save_image/main.cc
  include/ignition/sensors/AirPressureSensor.hh
  include/ignition/sensors/AltimeterSensor.hh
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Lidar.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/MagnetometerSensor.hh
  include/ignition/sensors/Manager.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Manager.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: beta, enhancement, 🔮 dome

#48 Bump ign-math to 6.6, add migration and changelog
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🔮 dome

#51 Corrected link address
  README.md
Labels: 🔮 dome

#50 Move installation instructions from README.md to Installation tutorial
  README.md
  tutorials.md.in
  tutorials/02_install.md
Labels: 🔮 dome

#52 Prepare for 4.0.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome
