Repository gazebosim/gz-sensors, pull requests merged in 2020-12, with the labels that each got.

#58 Removed windows warnings
  examples/save_image/main.cc
  include/ignition/sensors/AirPressureSensor.hh
  include/ignition/sensors/AltimeterSensor.hh
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImageGaussianNoiseModel.hh
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Lidar.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/MagnetometerSensor.hh
  include/ignition/sensors/Manager.hh
  include/ignition/sensors/RenderingEvents.hh
  include/ignition/sensors/RenderingSensor.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/SensorFactory.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImageGaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/MagnetometerSensor.cc
  src/Noise.cc
  src/PointCloudUtil.hh
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/ThermalCameraSensor.cc
  test/gtest/src/gtest.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: Windows, enhancement, tests, 🔮 dome

#69 Avoid moving a return value, it might prevent (N)RVO
  src/SensorFactory.cc
Labels: bug, 🔮 dome

#70 ⬆️ 2.9.1 🏁
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint
