Repository gazebosim/gz-sensors, pull requests merged in 2021-06, with the labels that each got.

#132 Remove clamping from lidar noise
  src/Lidar.cc
Labels: 🔮 dome

#137 Init will now set the nextUpdateTime to zero
  include/ignition/sensors/Sensor.hh
  src/Sensor.cc
Labels: 🔮 dome

#138 3 -> 4
  .github/workflows/ci.yml
  CMakeLists.txt
  test/integration/gpu_lidar_sensor_plugin.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cppcheck_rules/header_guard.rule
  tools/cppcheck_rules/namespace_AZ.rule
  tools/cpplint.py
Labels: 🔮 dome

#139 4 -> 5
  .github/workflows/ci.yml
  CMakeLists.txt
  include/ignition/sensors/Sensor.hh
  src/Lidar.cc
  src/Sensor.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cppcheck_rules/header_guard.rule
  tools/cppcheck_rules/namespace_AZ.rule
  tools/cpplint.py
Labels: 🏢 edifice

#140 5 -> 6 (main)
  CMakeLists.txt
  include/ignition/sensors/Sensor.hh
  src/Lidar.cc
  src/Sensor.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cppcheck_rules/header_guard.rule
  tools/cppcheck_rules/namespace_AZ.rule
  tools/cpplint.py
Labels: 🏯 fortress

#141 Remove deprecations: tock
  include/ignition/sensors/AirPressureSensor.hh
  include/ignition/sensors/AltimeterSensor.hh
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Lidar.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/MagnetometerSensor.hh
  include/ignition/sensors/Manager.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Manager.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/logical_camera_plugin.cc
Labels: 🏯 fortress
