Repository gazebosim/gz-sensors, pull requests merged in 2021-09, with the labels that each got.

#153 3 ➡️ 4
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  include/ignition/sensors/Sensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
Labels: 🔮 dome, beta

#154 4 ➡️ 5
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Sensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
Labels: beta, 🏢 edifice

#156 Update test config to run ogre 1.x tests in ign-sensors6 on macOS
  test/test_config.h.in
Labels: macOS, beta, 🏯 fortress

#155 5 ➡️ 6 (main)
  Changelog.md
  bitbucket-pipelines.yml
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Sensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
Labels: beta, 🏯 fortress

#133 Segmentation Sensor
  include/ignition/sensors/SegmentationCameraSensor.hh
  src/CMakeLists.txt
  src/SegmentationCameraSensor.cc
  test/integration/CMakeLists.txt
  test/integration/segmentation_camera.cc
  test/sdf/segmentation_camera_sensor_builtin.sdf
  tutorials.md.in
  tutorials/files/segmentation_camera/cars_segmentation.png
  tutorials/files/segmentation_camera/segmentation_dataset.gif
  tutorials/files/segmentation_camera/segmentation_images.png
  tutorials/install.md
  tutorials/intro.md
  tutorials/segmentation_camera.md
  tutorials/thermal_camera.md
Labels: needs upstream release, beta, 🏯 fortress

#144 Joint Force-Torque Sensor
  include/ignition/sensors/ForceTorqueSensor.hh
  include/ignition/sensors/SensorTypes.hh
  src/CMakeLists.txt
  src/ForceTorqueSensor.cc
  test/integration/CMakeLists.txt
  test/integration/air_pressure.cc
  test/integration/altimeter.cc
  test/integration/force_torque.cc
  test/integration/imu.cc
  test/integration/magnetometer.cc
Labels: beta, 🏯 fortress

#159 6.0.0~pre1
  Changelog.md
Labels: 🏯 fortress

#160 Trivial tutorial typo correction
  tutorials/custom_sensors.md
Labels: 🏯 fortress
