Repository gazebosim/gz-sensors, pull requests merged in 2021-04, with the labels that each got.

#121 👩‍🌾 Disable tests that consistently fail on macOS
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/rgbd_camera_plugin.cc
Labels: macOS, tests, 🏰 citadel

#122 👩‍🌾 3 ➡️ 4
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/rgbd_camera_plugin.cc
Labels: 🔮 dome

#124 Disable macos workflow
  .github/disabled_workflows/macos.yml
Labels: 🏯 fortress

#123 👩‍🌾 4 ➡️ 5
  .github/disabled_workflows/macos.yml
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/rgbd_camera_plugin.cc
Labels: 🏢 edifice

#126 Changelog fix
  Changelog.md
Labels: documentation, 🏢 edifice

#125 👩‍🌾 5 ➡️ 6
  .github/disabled_workflows/macos.yml
  Changelog.md
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/rgbd_camera_plugin.cc
Labels: 🏯 fortress
