Repository gazebosim/gz-sensors, pull requests merged in 2021-01, with the labels that each got.

#75 Bump in edifice: ign-msgs7
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🏢 edifice

#76 3 ➡️ 4
  CMakeLists.txt
  tutorials.md.in
  tutorials/files/thermal_camera/hot_object_behind_cool_object.png
  tutorials/files/thermal_camera/thermal_camera_demo.png
  tutorials/files/thermal_camera/thermal_camera_demo_2.png
  tutorials/thermal_camera.md
Labels: 🔮 dome

#77 4 ➡️ 5
  .github/workflows/macos.yml
  CMakeLists.txt
  examples/save_image/main.cc
  include/ignition/sensors/AirPressureSensor.hh
  include/ignition/sensors/AltimeterSensor.hh
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImageGaussianNoiseModel.hh
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Lidar.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/MagnetometerSensor.hh
  include/ignition/sensors/Manager.hh
  include/ignition/sensors/RenderingEvents.hh
  include/ignition/sensors/RenderingSensor.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/SensorFactory.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImageGaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/MagnetometerSensor.cc
  src/Noise.cc
  src/PointCloudUtil.hh
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/SensorFactory.cc
  src/ThermalCameraSensor.cc
  test/gtest/src/gtest.cc
  test/integration/CMakeLists.txt
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
  tutorials.md.in
  tutorials/files/thermal_camera/hot_object_behind_cool_object.png
  tutorials/files/thermal_camera/thermal_camera_demo.png
  tutorials/files/thermal_camera/thermal_camera_demo_2.png
  tutorials/thermal_camera.md
Labels: 🏢 edifice

#78 Bump in edifice: sdformat11
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🏢 edifice

#82 Add Windows Installation
  README.md
  tutorials/02_install.md
Labels: 🏰 citadel
