Repository gazebosim/gz-sensors, pull requests merged in 2021-03, with the labels that each got.

#102 👩‍🌾 Clear Windows warnings (backport #58)
  examples/save_image/main.cc
  include/ignition/sensors/AirPressureSensor.hh
  include/ignition/sensors/AltimeterSensor.hh
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImageGaussianNoiseModel.hh
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Lidar.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/MagnetometerSensor.hh
  include/ignition/sensors/Manager.hh
  include/ignition/sensors/RenderingEvents.hh
  include/ignition/sensors/RenderingSensor.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/Sensor.hh
  include/ignition/sensors/SensorFactory.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImageGaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/MagnetometerSensor.cc
  src/Noise.cc
  src/PointCloudUtil.hh
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor.cc
  src/ThermalCameraSensor.cc
  test/gtest/src/gtest.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: 🏰 citadel

#108 3 ➡️ 4
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
Labels: 🔮 dome

#110 4 ➡️ 5
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
  tutorials/03_thermal_camera.md
  tutorials/files/thermal_camera/hot_object_behind_cool_object.png
  tutorials/files/thermal_camera/thermal_camera_demo.png
  tutorials/files/thermal_camera/thermal_camera_demo_2.png
  tutorials/files/thermal_camera/thermal_camera_demo_3.png
  tutorials/thermal_camera.md
Labels: beta, 🏢 edifice

#89 Apply noise evenly to scans and point clouds
  include/ignition/sensors/Lidar.hh
  src/GpuLidarSensor.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
Labels: beta, 🏢 edifice

#112 🎈 5.0.0~pre1
  Changelog.md
Labels: beta, 🏢 edifice

#114 Revert "Apply noise evenly to scans and point clouds (#89)" and prep for 5.0.0~pre2
  CMakeLists.txt
  Changelog.md
  include/ignition/sensors/Lidar.hh
  src/GpuLidarSensor.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
Labels: beta, bug, 🏢 edifice

#117 Update Readme
  README.md
Labels: 🏢 edifice
