Repository gazebosim/gz-sensors, pull requests merged in 2021-02, with the labels that each got.

#88 3 to 4
  README.md
  tutorials/02_install.md
Labels: 🔮 dome

#91 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#86 Apply noise to lidar point cloud
  include/ignition/sensors/Lidar.hh
  src/GpuLidarSensor.cc
  src/Lidar.cc
Labels: 🏰 citadel

#93 3 to 4 20210208
  .github/workflows/macos.yml
  include/ignition/sensors/Lidar.hh
  src/GpuLidarSensor.cc
  src/Lidar.cc
Labels: 🔮 dome

#94 Prepare fo 3.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#95 Add set_rate service to all sensors
  src/CMakeLists.txt
  src/Sensor.cc
  src/Sensor_TEST.cc
Labels: enhancement, 🔮 dome

#96 3 to 4 20210211
  Changelog.md
Labels: 🔮 dome

#97 4-1-0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#99 Removed issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#101 Backport of #60: Fix macOS/windows tests that failed to load library
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/air_pressure_plugin.cc
  test/integration/altimeter_plugin.cc
  test/integration/camera_plugin.cc
  test/integration/depth_camera_plugin.cc
  test/integration/gpu_lidar_sensor_plugin.cc
  test/integration/imu_plugin.cc
  test/integration/logical_camera_plugin.cc
  test/integration/magnetometer_plugin.cc
  test/integration/rgbd_camera_plugin.cc
  test/integration/thermal_camera_plugin.cc
Labels: 🏰 citadel

#85 Bump in edifice: ign-common4
  .github/ci/packages.apt
  .github/workflows/macos.yml
  CMakeLists.txt
  bitbucket-pipelines.yml
  src/Sensor.cc
Labels: needs upstream release, 🏢 edifice

#79 Updated thermal camera tutorial: include varying temperature objects
  tutorials/03_thermal_camera.md
  tutorials/files/thermal_camera/hot_object_behind_cool_object.png
  tutorials/files/thermal_camera/thermal_camera_demo.png
  tutorials/files/thermal_camera/thermal_camera_demo_2.png
  tutorials/files/thermal_camera/thermal_camera_demo_3.png
  tutorials/thermal_camera.md
Labels: 🔮 dome
