Repository gazebosim/gz-sensors, pull requests merged in 2021-08, with the labels that each got.

#90 Remove plugin interface and support custom sensors
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  bitbucket-pipelines.yml
  examples/custom_sensor/CMakeLists.txt
  examples/custom_sensor/Odometer.cc
  examples/custom_sensor/Odometer.hh
  examples/custom_sensor/README.md
  examples/loop_sensor/CMakeLists.txt
  examples/loop_sensor/README.md
  examples/loop_sensor/main.cc
  examples/loop_sensor/sensors.sdf
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/Manager.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/SensorFactory.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  include/ignition/sensors/Util.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Manager.cc
  src/Manager_TEST.cc
  src/RgbdCameraSensor.cc
  src/SensorFactory.cc
  src/ThermalCameraSensor.cc
  src/Util.cc
  src/Util_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/air_pressure.cc
  test/integration/altimeter.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_lidar_sensor.cc
  test/integration/imu.cc
  test/integration/logical_camera.cc
  test/integration/magnetometer.cc
  test/integration/rgbd_camera.cc
  test/integration/thermal_camera.cc
  test/sdf/camera_sensor_builtin.sdf
  test/sdf/custom_sensors.sdf
  test/sdf/depth_camera_sensor_builtin.sdf
  test/sdf/rgbd_camera_sensor_builtin.sdf
  test/sdf/thermal_camera_sensor_8bit_builtin.sdf
  test/sdf/thermal_camera_sensor_builtin.sdf
  tutorials.md.in
  tutorials/02_install.md
  tutorials/custom_sensors.md
Labels: enhancement, 🏯 fortress

#146 Publish performance sensor metrics.
  include/ignition/sensors/Sensor.hh
  src/Sensor.cc
  src/Sensor_TEST.cc
Labels: 🏰 citadel, needs upstream release, performance

#150 👩‍🌾 Remove bitbucket-pipelines.yml
  bitbucket-pipelines.yml
Labels: 🏰 citadel

#152 🎈 3.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel
