Repository gazebosim/gz-sensors, pull requests merged in 2021-12, with the labels that each got.

#173 Bumps in garden : ci_matching_branch/bump_garden_ign-sensors7
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🌱 garden

#181 🎈 4.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#178 IMU ``custom_rpy`` tag parsing added
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
Labels: 🏯 fortress

#180 Added Logic to flag pointcloud if invalid point is Detected
  Migration.md
  src/GpuLidarSensor.cc
  test/integration/gpu_lidar_sensor.cc
Labels: bug, 🏯 fortress

#183 Bumps in garden: ign-math7, ign-common5, sdformat13
  .github/ci/packages.apt
  CMakeLists.txt
  include/ignition/sensors/ForceTorqueSensor.hh
  include/ignition/sensors/SegmentationCameraSensor.hh
  src/Sensor_TEST.cc
Labels: 🌱 garden
