Repository gazebosim/gz-sensors, pull requests merged in 2022-05, with the labels that each got.

#220 Add support for single channel 8 bit grayscale image format
  src/CameraSensor.cc
  test/integration/camera.cc
  test/sdf/camera_sensor_l8_builtin.sdf
Labels: 🏯 fortress

#215 [fortress] Fix triggered camera test
  src/CameraSensor.cc
  test/integration/triggered_camera.cc
  test/sdf/triggered_camera_sensor_builtin.sdf
Labels: 🏯 fortress

#224 Sets lidar visibility mask
  include/ignition/sensors/Lidar.hh
  src/GpuLidarSensor.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
Labels: needs upstream release, 🏯 fortress

#225 Prepare for 6.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#222 Add HasConnections function
  include/ignition/sensors/AirPressureSensor.hh
  include/ignition/sensors/AltimeterSensor.hh
  include/ignition/sensors/CameraSensor.hh
  include/ignition/sensors/DepthCameraSensor.hh
  include/ignition/sensors/ForceTorqueSensor.hh
  include/ignition/sensors/GpuLidarSensor.hh
  include/ignition/sensors/ImuSensor.hh
  include/ignition/sensors/Lidar.hh
  include/ignition/sensors/LogicalCameraSensor.hh
  include/ignition/sensors/MagnetometerSensor.hh
  include/ignition/sensors/NavSatSensor.hh
  include/ignition/sensors/RgbdCameraSensor.hh
  include/ignition/sensors/SegmentationCameraSensor.hh
  include/ignition/sensors/ThermalCameraSensor.hh
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/ForceTorqueSensor.cc
  src/GpuLidarSensor.cc
  src/ImuSensor.cc
  src/Lidar.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/NavSatSensor.cc
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/SegmentationCameraSensor.cc
  src/ThermalCameraSensor.cc
  test/integration/air_pressure.cc
  test/integration/altimeter.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/force_torque.cc
  test/integration/gpu_lidar_sensor.cc
  test/integration/imu.cc
  test/integration/logical_camera.cc
  test/integration/magnetometer.cc
  test/integration/navsat.cc
  test/integration/rgbd_camera.cc
  test/integration/segmentation_camera.cc
  test/integration/thermal_camera.cc
  test/integration/triggered_camera.cc
Labels: 🏯 fortress

#228 🎈 6.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#230 Remove deprecated common/PluginMacros.hh include
  include/gz/sensors/SegmentationCameraSensor.hh
Labels: 🌱 garden
