Repository gazebosim/gz-sensors, pull requests merged in 2022-07, with the labels that each got.

#243 Disable thermal camera test on MacOS
  test/integration/thermal_camera.cc
Labels: macOS, tests, 🏯 fortress

#235 ign -> gz Shared Lib Migration : gz-sensors
  Migration.md
  examples/custom_sensor/Odometer.cc
  examples/loop_sensor/sensors.sdf
  test/sdf/custom_sensors.sdf
  tutorials/custom_sensors.md
  tutorials/segmentation_camera.md
  tutorials/thermal_camera.md
Labels: 🌱 garden, ign to gz

#245 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, QA

#248 3 ➡️ 6
  README.md
Labels: 🏯 fortress

#242 Add missing msgs include statements
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/ForceTorqueSensor.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/MagnetometerSensor.cc
  src/NavSatSensor.cc
  src/Sensor.cc
Labels: bug, 🌱 garden

#246 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  include/ignition/sensors/config.hh.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: bug, ign to gz

#251 Merge ign-sensors2 ➡️ ign-sensors3
  CMakeLists.txt
  Changelog.md
  api.md.in
  include/ignition/sensors/config.hh.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: 🏰 citadel
