Repository gazebosim/gz-sensors, pull requests merged in 2022-06, with the labels that each got.

#231 Use pose multiplication instead of subtraction
  src/LogicalCameraSensor.cc
  test/integration/logical_camera.cc
Labels: 🌱 garden

#210 [garden] Use anti-aliasing value from <anti_aliasing> SDF element
  Migration.md
  src/CameraSensor.cc
Labels: 🌱 garden

#237 [ign -> gz] CMake functions
  CMakeLists.txt
  include/gz/sensors/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#136 Add BoundingBox Sensor
  CMakeLists.txt
  include/ignition/sensors/BoundingBoxCameraSensor.hh
  src/BoundingBoxCameraSensor.cc
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/boundingbox_camera.cc
  test/sdf/boundingbox_3d_camera_sensor_builtin.sdf
  test/sdf/boundingbox_camera_sensor_builtin.sdf
  tutorials/04_boundingbox_camera.md
  tutorials/files/boundingbox_camera/boundingbox_camera_full.png
  tutorials/files/boundingbox_camera/boundingbox_camera_visible.png
  tutorials/files/boundingbox_camera/object_detection_dataset.gif
  tutorials/files/boundingbox_camera/visualize_2d.png
  tutorials/files/boundingbox_camera/visualize_3d.png
Labels: 🏯 fortress

#238 🎈 6.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#233 Rename CMake project to gz
  CMakeLists.txt
  doc/CMakeLists.txt
  examples/custom_sensor/CMakeLists.txt
  examples/imu_noise/CMakeLists.txt
  examples/loop_sensor/CMakeLists.txt
  examples/save_image/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#240 ign -> gz Partial Docs Migration and Project Name Followups : gz-sensors
  Changelog.md
  Migration.md
  README.md
  api.md.in
  examples/save_image/main.cc
  src/RgbdCameraSensor.cc
  tutorials.md.in
  tutorials/custom_sensors.md
  tutorials/install.md
  tutorials/intro.md
  tutorials/segmentation_camera.md
  tutorials/thermal_camera.md
Labels: 🌱 garden, ign to gz
