Repository gazebosim/gz-sensors, pull requests merged in 2022-11, with the labels that each got.

#249 Camera: configure projection matrix from SDFormat
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/Camera_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/camera_plugin.cc
  test/integration/camera_sensor_builtin.sdf
Labels: enhancement, 🏰 citadel

#280 RgbdCameraSensor.cc: fix include
  src/RgbdCameraSensor.cc
Labels: 🏰 citadel

#282 Merge ign-sensors3 ➡️ ign-sensors6
  Changelog.md
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/DepthCameraSensor.cc
  src/GaussianNoiseModel.cc
  src/GpuLidarSensor.cc
  src/ImageGaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Manager.cc
  src/Noise_TEST.cc
  src/PointCloudUtil.hh
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/SensorTypes.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
  test/integration/CMakeLists.txt
  test/integration/rgbd_camera.cc
  test/sdf/camera_sensor_builtin.sdf
Labels: 🏯 fortress

#283 Merge ign-sensors6 ➡️ gz-sensors7
  Changelog.md
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/DepthCameraSensor.cc
  src/GaussianNoiseModel.cc
  src/GpuLidarSensor.cc
  src/ImageGaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Manager.cc
  src/Noise_TEST.cc
  src/PointCloudUtil.hh
  src/RenderingSensor.cc
  src/RgbdCameraSensor.cc
  src/SensorTypes.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
  test/integration/CMakeLists.txt
  test/integration/camera.cc
  test/integration/rgbd_camera.cc
  test/sdf/camera_sensor_builtin.sdf
  test/sdf/camera_sensor_l16_builtin.sdf
Labels: 🌱 garden

#281 Update Camera Intrinsics in camera_info topic
  src/CameraSensor.cc
  test/integration/camera.cc
  test/sdf/camera_intrinsics.sdf
Labels: 🌱 garden

#291 3.5.0 pre1
  CMakeLists.txt
Labels: 🏰 citadel
