Repository gazebosim/gz-sensors, pull requests merged in 2022-08, with the labels that each got.

#252 Merge ign-sensors3 ➡️ ign-sensors6
  CMakeLists.txt
  Changelog.md
  api.md.in
  include/ignition/sensors/config.hh.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: 🏯 fortress

#247 Merge ign-sensors6 ➡️ main
  Changelog.md
  README.md
  include/gz/sensors/BoundingBoxCameraSensor.hh
  include/ignition/sensors/BoundingBoxCameraSensor.hh
  src/BoundingBoxCameraSensor.cc
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/boundingbox_camera.cc
  test/integration/thermal_camera.cc
  test/sdf/boundingbox_3d_camera_sensor_builtin.sdf
  test/sdf/boundingbox_camera_sensor_builtin.sdf
  tutorials/04_boundingbox_camera.md
  tutorials/files/boundingbox_camera/boundingbox_camera_full.png
  tutorials/files/boundingbox_camera/boundingbox_camera_visible.png
  tutorials/files/boundingbox_camera/object_detection_dataset.gif
  tutorials/files/boundingbox_camera/visualize_2d.png
  tutorials/files/boundingbox_camera/visualize_3d.png
  tutorials/segmentation_camera.md
  tutorials/thermal_camera.md
Labels: enhancement, 🌱 garden

#253 Fix forward-port: use gz_add_component
  src/CMakeLists.txt
Labels: bug, 🌱 garden, ign to gz

#258 ign -> gz : Remove redundant namespace references
  src/AirPressureSensor.cc
  src/AltimeterSensor.cc
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GaussianNoiseModel.cc
  src/ImuSensor.cc
  src/ImuSensor_TEST.cc
  src/LogicalCameraSensor.cc
  src/MagnetometerSensor.cc
  src/Manager.cc
  src/Noise_TEST.cc
  src/RgbdCameraSensor.cc
  src/SensorFactory.cc
  src/SensorTypes.cc
  src/Sensor_TEST.cc
  src/ThermalCameraSensor.cc
  test/integration/rgbd_camera_plugin.cc
Labels: 🏰 citadel, ign to gz

#261 🎈 3.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#262 Add missing DEPENDS_ON_COMPONENTS parameters
  src/CMakeLists.txt
Labels: 🏰 citadel

#263 Fix msgs.hh uses
  examples/custom_sensor/Odometer.cc
  include/gz/sensors/CameraSensor.hh
  include/gz/sensors/DepthCameraSensor.hh
  include/gz/sensors/LogicalCameraSensor.hh
  include/gz/sensors/SegmentationCameraSensor.hh
  include/gz/sensors/ThermalCameraSensor.hh
  include/gz/sensors/WideAngleCameraSensor.hh
  src/BoundingBoxCameraSensor.cc
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/ImuSensor_TEST.cc
  src/Lidar_TEST.cc
  src/LogicalCameraSensor.cc
  src/RgbdCameraSensor.cc
  src/SegmentationCameraSensor.cc
  src/ThermalCameraSensor.cc
  src/WideAngleCameraSensor.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/distortion_camera.cc
  test/integration/gpu_lidar_sensor.cc
  test/integration/logical_camera.cc
  test/integration/rgbd_camera.cc
  test/integration/segmentation_camera.cc
  test/integration/thermal_camera.cc
  test/integration/triggered_camera.cc
  test/integration/wide_angle_camera.cc
Labels: bug, 🌱 garden, Breaking change
