Repository gazebosim/gz-sensors, pull requests merged in 2023-06, with the labels that each got.

#348 Fix dvl integration test
  src/Manager.cc
  test/integration/dvl.cc
Labels: 🎵 harmonic

#352 Minor cleanup
  include/gz/sensors/DepthCameraSensor.hh
  src/CameraSensor.cc
  src/GpuLidarSensor.cc
  src/NavSatSensor.cc
  src/SegmentationCameraSensor.cc
  src/Sensor.cc
Labels: 🌱 garden

#351 Fix finding GzProtobuf to support version 4.23.2
  CMakeLists.txt
Labels: 🏯 fortress

#353 Backport #351: Support protobuf >= 22
  CMakeLists.txt
Labels: 🏰 citadel

#355 Merge ign-sensors6 ➡️ gz-sensors7
  CMakeLists.txt
Labels: 🌱 garden

#356 Merge gz-sensors7 ➡️ main
  CMakeLists.txt
  include/gz/sensors/DepthCameraSensor.hh
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
  src/NavSatSensor.cc
  src/SegmentationCameraSensor.cc
  src/Sensor.cc
Labels: 🎵 harmonic
