Repository gazebosim/gz-sensors, pull requests merged in 2023-09, with the labels that each got.

#376 Prepare for 6.7.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#378 Update README.md
  README.md
Labels: 🎵 harmonic

#381 Update reference to gazebo classic in introduction
  tutorials/intro.md
Labels: 🎵 harmonic

#379 Minor updates to the thermal camera tutorial
  tutorials/thermal_camera.md
Labels: 🎵 harmonic

#382 Replace ign with gz in installation tutorial
  tutorials/install.md
Labels: 🎵 harmonic

#385 Use Jammy CI status badge in README
  README.md
Labels: 🎵 harmonic

#387 Merge 7 -> 8
  .github/workflows/triage.yml
  Changelog.md
  include/gz/sensors/CameraSensor.hh
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
Labels: beta, 🎵 harmonic

#388 Prepare for 8.0.0~pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#389 Prepare for 8.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
