Repository gazebosim/gz-sensors, pull requests merged in 2023-08, with the labels that each got.

#371 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#372 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden

#366 remove ignition
  src/Lidar.cc
  test/integration/deprecated_TEST.cc
Labels: 🎵 harmonic

#367 Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-sensors8
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🎵 harmonic

#374 Update air sensor with air_speed.proto
  src/AirSpeedSensor.cc
  test/integration/air_speed.cc
Labels: beta, 🎵 harmonic

#375 Tests need to include message types they are using
  src/BoundingBoxCameraSensor.cc
  test/integration/air_pressure.cc
  test/integration/air_speed.cc
  test/integration/altimeter.cc
  test/integration/boundingbox_camera.cc
  test/integration/camera.cc
  test/integration/dvl.cc
  test/integration/force_torque.cc
  test/integration/imu.cc
  test/integration/magnetometer.cc
  test/integration/navsat.cc
  test/integration/segmentation_camera.cc
  test/integration/triggered_boundingbox_camera.cc
  test/integration/wide_angle_camera.cc
Labels: 🎵 harmonic

#333 populate the covariance fields using the noise models
  src/ImuSensor.cc
Labels: needs upstream release, beta, 🌱 garden
