Repository gazebosim/gz-sensors, pull requests merged in 2023-03, with the labels that each got.

#330 Fix links in Changelog
  Changelog.md
Labels: 🏰 citadel

#327 3 -> 6
  src/CameraSensor.cc
  src/Camera_TEST.cc
Labels: 🏯 fortress

#331 6 -> 7
  Changelog.md
  src/CameraSensor.cc
  src/Camera_TEST.cc
  src/RenderingSensor.cc
  test/integration/boundingbox_camera.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_lidar_sensor.cc
  test/integration/rgbd_camera.cc
  test/integration/segmentation_camera.cc
  test/integration/thermal_camera.cc
  test/integration/triggered_boundingbox_camera.cc
Labels: 🌱 garden

#334 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#335 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#338 Merge ign-sensors6 ➡️ gz-sensors7
  .github/disabled_workflows/macos.yml
  .github/workflows/ci.yml
  COPYING
  Changelog.md
  LICENSE
Labels: 🌱 garden
