Repository gazebosim/gz-sensors, pull requests merged in 2023-02, with the labels that each got.

#289 Added projection values from camera when are not defined in the SDF
  src/CameraSensor.cc
  test/integration/camera.cc
  test/sdf/camera_projection.sdf
Labels: needs upstream release

#305 Added airspeed sensor
  CMakeLists.txt
  include/gz/sensors/AirSpeedSensor.hh
  include/gz/sensors/SensorTypes.hh
  src/AirSpeedSensor.cc
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/air_speed.cc
Labels: 🌱 garden

#315 Prepare for 7.1.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#320 6.7.0 prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#314 Set custom projection values from sdf
  CMakeLists.txt
  src/CameraSensor.cc
  test/integration/camera.cc
  test/sdf/camera_intrinsics.sdf
  test/sdf/camera_projection.sdf
Labels: 🌱 garden

#285 Added Camera Info topic support for cameras
  src/CameraSensor.cc
  src/Camera_TEST.cc
Labels: 🏰 citadel, needs upstream release

#323 6.7.0 release
  CMakeLists.txt
Labels: 🏯 fortress

#324 Fix rendering tests on Jammy
  src/RenderingSensor.cc
  test/integration/boundingbox_camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_lidar_sensor.cc
  test/integration/rgbd_camera.cc
  test/integration/segmentation_camera.cc
  test/integration/thermal_camera.cc
Labels: 🏯 fortress

#322 Added trigger to BoundingBoxCamera
  include/gz/sensors/BoundingBoxCameraSensor.hh
  include/gz/sensors/CameraSensor.hh
  src/BoundingBoxCameraSensor.cc
  src/CameraSensor.cc
  test/integration/CMakeLists.txt
  test/integration/triggered_boundingbox_camera.cc
  test/sdf/triggered_boundingbox_camera_sensor_builtin.sdf
Labels: 🌱 garden

#326 Fix Camera info test
  src/Camera_TEST.cc
Labels: 🏰 citadel

#329 Fix flaky bounding box camera test
  src/BoundingBoxCameraSensor.cc
  test/integration/triggered_boundingbox_camera.cc
Labels: 🌱 garden
