Repository gazebosim/gz-sensors, pull requests merged in 2024-01, with the labels that each got.

#407 Prepare for 3.6.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#408 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#409 Allow specifying gz_frame_id as an alternative to ignition_frame_id
  src/Sensor.cc
  src/Sensor_TEST.cc
Labels: 🏯 fortress

#410 Merge ign-sensors3 ➡️ ign-sensors6
  Changelog.md
Labels: 🏯 fortress

#411 Prepare for 6.8.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#412 Merge ign-sensors6 ➡️ gz-sensors7
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  src/CameraSensor.cc
  src/Sensor_TEST.cc
  test/integration/camera.cc
Labels: 🌱 garden

#413 DepthCamera and RGBDCamera - optimize RGB point cloud connection
  src/DepthCameraSensor.cc
  src/RgbdCameraSensor.cc
Labels: 🎵 harmonic

#414 Merge 7 ➡️ 8
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  src/CameraSensor.cc
  src/Sensor_TEST.cc
  test/integration/camera.cc
Labels: 🎵 harmonic
