Repository gazebosim/gz-sensors, pull requests merged in 2024-03, with the labels that each got.

#417 Fix frames set to Name instead of FrameId for pointclouds
  src/DepthCameraSensor.cc
  src/GpuLidarSensor.cc
Labels: 🏯 fortress

#419 Prepare for 8.0.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#418 Merge 8 -> main
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  README.md
  src/CameraSensor.cc
  src/DepthCameraSensor.cc
  src/RgbdCameraSensor.cc
  src/Sensor_TEST.cc
  test/integration/camera.cc
Labels: 🏛️ ionic

#420 [backport harmonic] Avoid calling DblNormal with invalid standard deviation (#396)
  src/GaussianNoiseModel.cc
Labels: 🎵 harmonic

#421 Prepare for 8.0.1 Release (v2)
  Changelog.md
Labels: 🎵 harmonic
