Repository gazebosim/gz-sensors, pull requests merged in 2025-05, with the labels that each got.

#519 ci.yml: check doxygen on 24.04
  .github/workflows/ci.yml
  tutorials/boundingbox_camera.md
  tutorials/segmentation_camera.md
Labels: 🏛️ ionic

#520 Update CameraSensor.ccAllow HFOV narrower than 0.5°
  src/CameraSensor.cc
Labels: 🏛️ ionic

#523 Clarify min and max temperature of thermal camera
  tutorials/thermal_camera.md
Labels: 🎵 harmonic

#524 Merge gz-sensors9 ➡️ main
  include/gz/sensors/AirSpeedSensor.hh
  src/AirSpeedSensor.cc
Labels: 🪵 jetty

#526 Update API to return const references to strings
  include/gz/sensors/CameraSensor.hh
  include/gz/sensors/Sensor.hh
  src/CameraSensor.cc
  src/Sensor.cc
Labels: 🪵 jetty

#525 Bump gz-cmake and others in jetty
  .github/ci/packages.apt
  CMakeLists.txt
  examples/custom_sensor/CMakeLists.txt
  examples/save_image/CMakeLists.txt
  package.xml
  src/CMakeLists.txt
  src/CameraSensor.cc
  src/RgbdCameraSensor.cc
  tutorials/thermal_camera.md
Labels: 🪵 jetty

#527 Disable ign-sensors6's (fortress) failing tests on Windows
  test/integration/boundingbox_camera.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_lidar_sensor.cc
  test/integration/rgbd_camera.cc
  test/integration/segmentation_camera.cc
  test/integration/thermal_camera.cc
  test/integration/triggered_camera.cc
Labels: 🏯 fortress
